### ISSUE TITLE
Is android-L required?

### ISSUE THREAD

**Issue by ghost** [gringer/ColourClock#1]
I added your build to fdroid, however we currently do not have android-L installed as it is pre-release. Is it really needed to build this app?

**Comment by AmauryEsparza** [comment]
The min sdk is 16 (Android 4.1)

**Comment by ghost** [comment]
Indeed, but minSdk is a runtime requirement and I am trying to build with a lower compileSdk and targetSdk and run into errors like...

```
src/fdroiddata/build/org.gringene.colourclock/app/build/intermediates/res/release/values-v21/values.xml:7: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'
```

...if I force a lower SDK.

**Comment by gringer** [comment]
Sorry, I'm a bit green to development and recently discovered the target SDK must be an integer for released versions, not a character (L is an unreleased developer version). I'll be fixing that shortly.

**Comment by gringer** [comment]
Okay, hopefully that's fixed. Please adjust the fdroid metadata to commit 7a7e2edbfb, and version 1.1.1. I've managed to work out how to tag releases as well (as v<release>), so that flag can probably now be set.

**Comment by ghost** [comment]
Thanks for quick fixing this.  Regarding tags: I adjusted our build to auto-update your two clock apps ( as long as you update versionCode and versionName and then tag the release with "v" + versionName.
